[project]
name = "learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.14"
dependencies = [
    "asyncio>=4.0.0",
    "claude-agent-sdk>=0.1.36",
    "python-dotenv>=1.2.1",
]
